### ISSUE TITLE
[question not related to this repo] how to contact ?

### ISSUE THREAD

**Issue by fulcanelly** [narumincho/commection#8]
Is there way to contact you ? email, telegram or discord ?

I just want invite you to play minecraft together but could not find any contact info

**Comment by narumincho** [comment]
Most of my Minecraft activities take place at 「もりのパーティ」. 

First, join the Minecraft server 「もりのパーティ」 at the address `visit.morino.party` and do the tutorial.

Next, join 「もりのパーティ」 Discord server via the Discord invite link at https://morino.party/discord. You will find me there.
